[build]
  # Явно указываем пустую команду, чтобы избежать ошибок с поиском сборщика
  command = ""
  # Публиковать все из корневой директории
  publish = "/"

# Заголовки
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Language = "ru"
    Cache-Control = "max-age=3600, public"
