[build]
  # Поскольку это чистый HTML-файл без этапа компиляции (например, React или Vue),
  # команду сборки можно оставить пустой или использовать заглушку.
  command = "echo 'No build command needed for static HTML'"
  # Указываем, что файлы, которые нужно опубликовать, находятся в корневой директории
  publish = "/"

# Дополнительные заголовки для повышения безопасности и указания языка
[[headers]]
  for = "/*"
  [headers.values]
    # Защита от кликджекинга
    X-Frame-Options = "DENY"
    # Указание языка контента
    Content-Language = "ru"
    # Настройки для кэширования
    Cache-Control = "max-age=3600, public"
